<?php

namespace App\Controllers;

use App\Exceptions\DomainException;
use App\Helpers\Response;
use App\Services\CartService;
use App\Repositories\CartRepository;
use App\Repositories\CouponRepository;
use App\Repositories\ProductRepository;
use App\Services\CouponService;
use Throwable;

class CartController
{
    private CartService $cartService;
    public function __construct()
    {
        $this->cartService = new CartService(
            new CartRepository(),
            new ProductRepository,
            new CouponService(new CouponRepository)
        );
    }

    public function show(): void
    {
        try {
            $sessionId = $_SESSION["sessionId"];
            $cart = $this->cartService->getCart($sessionId);
            Response::success($cart, "Displays cart information generated by the session.");
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );
        } catch (Throwable $e) {
            print($e);
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }
    }

    public function add(): void
    {
        try {
            $sessionId = $_SESSION['sessionId'];
            $data = json_decode(file_get_contents('php://input'), true);
            $productId = (int) $data['product_id'];
            $quantity  = (int) ($data['quantity'] ?? 1);

            $cart = $this->cartService->addProduct(
                $sessionId,
                $productId,
                $quantity
            );

            Response::success($cart, 'product added to cart');
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );
        } catch (Throwable $e) {
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }
    }

    public function cartProductUpdate(int $cartItemId): void
    {
        try {
            $sessionId = $_SESSION['sessionId'];
            $data = json_decode(file_get_contents('php://input'), true);
            $quantity = (int) ($data['quantity'] ?? 1);

            if ($quantity <= 0) {
                $this->removeCartItem($cartItemId);
            } else {
                $cart = $this->cartService->updateItemQuantity(
                    $sessionId,
                    $cartItemId,
                    $quantity
                );
            }

            Response::success($cart, 'cart item updated');
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );
        } catch (Throwable $e) {
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }
    }
    public function cartProductRemove(int $cartItemId): void
    {
        try {
            $this->removeCartItem($cartItemId);
            Response::success(null, 'cart item removed');
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );
        } catch (Throwable $e) {
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }
    }
    public function removeCartItem(int $cartItemId): void
    {
        try {
            $sessionId = $_SESSION['sessionId'];
            $this->cartService->removeCartItem($sessionId, $cartItemId);
            Response::success(null, 'The item has been removed from the cart');
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );
        } catch (Throwable $e) {
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }
    }

    public function remove(): void
    {
        try {
            $sessionId = $_SESSION['sessionId'];
            $this->cartService->removeAllCartItem($sessionId);
            Response::success(null, 'All item have been removed from the cart');
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );
        } catch (Throwable $e) {
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }
    }

    public function applyCoupon() :void
    {
        try {
            $sessionId = $_SESSION['sessionId'];
            $data = json_decode(file_get_contents('php://input'), true);
            $couponCode = $data['coupon_code'];
            $cart = $this->cartService->applyCoupon($sessionId,$couponCode);
            Response::success($cart, 'Coupon applied to cart');
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );
        } catch (Throwable $e) {
            print($e);
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }

    }
    public function removeCoupon(): void {
        try {
            $sessionId = $_SESSION['sessionId'];
            $cart = $this->cartService->removeCoupon($sessionId);
            Response::success($cart, 'Coupon removed to cart');
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );
        } catch (Throwable $e) {
            print_r($e);
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }
    }
}
