<?php

namespace App\Controllers;

use App\Helpers\Response;
use App\Services\CartService;
use App\Repositories\CartRepository;
use App\Repositories\ProductRepository;

class CartController
{
    private CartService $cartService;
    public function __construct()
    {
        $this->cartService = new CartService(
            new CartRepository(), new ProductRepository
        );
    }

    public function show() :void{
        $sessionId = $_SESSION["sessionId"];
        $cart = $this->cartService->getCart($sessionId);
        Response::success($cart,"Displays cart information generated by the session.");
    }

    public function add() :void{
        $sessionId = $_SESSION['sessionId'];

        $data = json_decode(file_get_contents('php://input'), true);

        $productId = (int) $data['product_id'];
        $quantity  = (int) ($data['quantity'] ?? 1);

        $cart = $this->cartService->addProduct(
            $sessionId,
            $productId,
            $quantity
        );

        Response::success($cart, 'product added to cart');
    }

    public function cartProductUpdate(int $cartItemId) :void{
        $sessionId = $_SESSION['sessionId'];

        $data = json_decode(file_get_contents('php://input'), true);
        $quantity = (int) ($data['quantity'] ?? 1);

       if ($quantity <= 0) {
            $this->removeCartItem($cartItemId);
        }
        else{
            $cart = $this->cartService->updateItemQuantity(
                        $sessionId,
                        $cartItemId,
                        $quantity
                    );
        }

        Response::success($cart, 'cart item updated');
    }
    public function cartProductRemove(int $cartItemId) :void{
        $this->removeCartItem($cartItemId);
        Response::success(null, 'cart item removed');
    }
    public function removeCartItem(int $cartItemId): void
    {
        $sessionId = $_SESSION['sessionId'];
        $this->cartService->removeCartItem($sessionId,$cartItemId);
        
        Response::success(null, 'The item has been removed from the cart');
    }

    public function remove(): void
    {
        $sessionId = $_SESSION['sessionId'];
        $this->cartService->removeAllCartItem($sessionId);
        
        Response::success(null, 'All item have been removed from the cart');
    }

}