<?php

namespace App\Controllers;

use App\Exceptions\DomainException;
use App\Helpers\Response;
use App\Repositories\CartRepository;
use App\Repositories\CouponRepository;
use App\Services\CartService;
use App\Services\FavoriteService;
use App\Repositories\ProductRepository;
use App\Repositories\FavoriteRepository;
use App\Services\CouponService;
use Throwable;

class FavoriteController
{
    private FavoriteService $favoriteService;
    public function __construct()
    {
        $this->favoriteService = new FavoriteService(
            new FavoriteRepository, 
            new ProductRepository, 
            new CartService(
                            new CartRepository,
                            new ProductRepository,
                            new CouponService(new CouponRepository)
                            )
        );
    }

    public function show() :void{
        try{
            $sessionId = $_SESSION["sessionId"];
            $favorites = $this->favoriteService->getFavorites($sessionId);
            Response::success($favorites,"Displays favorite product information generated by the session.");
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );

        } catch (Throwable $e) {
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }

    }
	
	    public function addNewProduct() :void{
        try{
            $sessionId = $_SESSION['sessionId'];
            $data = json_decode(file_get_contents('php://input'), true);
            $productId = (int) $data['product_id'];
            $favorite = $this->favoriteService->addProduct($sessionId,$productId);

            Response::success($favorite, 'product added to favorite');
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );

        } catch (Throwable $e) {
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }
    }

    

    public function remove(int $productId): void
    {
        try{
            $sessionId = $_SESSION['sessionId'];
            $this->favoriteService->remove($sessionId,$productId);
            Response::success(null, 'Product remove from favorite');
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );

        } catch (Throwable $e) {
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }
    }
    public function addFavoriteProductToCart(int $productId) :void{
        try{
            $sessionId = $_SESSION['sessionId'];
            $favorite = $this->favoriteService->addFavoriteProductToCart($sessionId,$productId);

            Response::success($favorite, 'product added to favorite');
        } catch (DomainException $e) {
            Response::error(
                $e->getErrorCode(),
                $e->getMessage(),
                $e->getStatusCode()
            );

        } catch (Throwable $e) {
            Response::error(
                'INTERNAL_ERROR',
                'An unexpected error occurred.',
                500
            );
        }
    }
}